install:
  - wget https://github.com/Keats/gutenberg/releases/download/v0.3.0/gutenberg-v0.3.0-x86_64-unknown-linux-gnu.tar.gz
  - tar xf gutenberg-v0.2.2-x86_64-unknown-linux-gnu.tar.gz
  - chmod +x gutenberg

script:
  - ./gutenberg build

deploy:
  - provider: pages
    local_dir: public
    skip_cleanup: true
    github_token:
      secure: "n1OCiCjupkVieqsepGBOk6oxGcU89n9z0lQWWMAtBKREIEL1fnqt7A4z9FC1LV9UiAwvcvMHI8As5TA/7sV6jiWFuNOqu5HurX/n7cXlAuVWx00gCtWZ7Fh14ipVIDr2W52Mj/5qw1LSW19g8+9nLF1xO2YLrNpiaQX+V6Ypf04="
    on:
      branch: master
